apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: ubuntu-focal
spec:
  data: |
    version: "0.1"
    name: ubuntu_Focal
    global_timeout: 9800
    tasks:
      - name: "os-installation"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: stream-ubuntu-image
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/image2disk:1.2.2
            timeout: 9800
            environment:
              COMPRESSED: "true"
              IMG_URL: http://10.49.1.137:8081/jammy-server-cloudimg-amd64.img.raw.gz
              DEST_DISK: {{ index .Hardware.Disks 0 }}
          - name: create-user
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/cexec:1.2.2
            timeout: 90
            environment:
              CHROOT: "y"
              CMD_LINE: useradd -p $(openssl passwd -1 user) -s /bin/bash -d /home/user/ -m
                -G sudo user
              DEFAULT_INTERPRETER: /bin/sh -c
              FS_TYPE: ext4
          - name: add-env-proxy
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n\t\t\t\t\t\thttp_proxy=http://proxy-dmz.intel.com:912\n\t\t\t\t\t\thttps_proxy=http://proxy-dmz.intel.com:912\n\t\t\t\t\t\tno_proxy=localhost,127.0.0.1,intel.com,.internal,10.0.0.0/8,.cluster.local,.cluster.onprem"
              DEST_PATH: /etc/environment
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: add-apt-proxy
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n\t\t\t\t\t\tAcquire::http::Proxy \"http://proxy-dmz.intel.com:912\";\n\t\t\t\t\t\tAcquire::https::Proxy
                \"http://proxy-dmz.intel.com:912\";"
              DEST_PATH: /etc/apt/apt.conf
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: "add cloud-init config"
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: |
                datasource:
                  NoCloud:
                    meta-data: |
                      instance-id: l-eadfbe
                    user-data: |
                      #cloud-config
                      runcmd: [ echo "it worked!" > /tmp/example.txt ]
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              DIRMODE: "0700"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0600"
              UID: "0"
          - name: "add cloud-init ds-identity"
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: NoCloud
