apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: ubuntu-focal
spec:
  data: |
    version: "0.1"
    name: ubuntu_Focal
    global_timeout: 9800
    tasks:
      - name: "os-installation"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: stream-ubuntu-image
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/image2disk:1.2.2
            timeout: 9800
            environment:
              COMPRESSED: "true"
              IMG_URL: http://10.49.1.137:8081/jammy-server-cloudimg-amd64.img.raw.gz
              DEST_DISK: {{ index .Hardware.Disks 0 }}
          - name: create-user
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/cexec:1.2.2
            timeout: 90
            environment:
              CHROOT: "y"
              CMD_LINE: useradd -p $(openssl passwd -1 user) -s /bin/bash -d /home/user/ -m
                -G sudo user
              DEFAULT_INTERPRETER: /bin/sh -c
              FS_TYPE: ext4
          - name: add-env-proxy
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n\t\t\t\t\t\thttp_proxy=http://proxy-dmz.intel.com:912\n\t\t\t\t\t\thttps_proxy=http://proxy-dmz.intel.com:912\n\t\t\t\t\t\tno_proxy=localhost,127.0.0.1,intel.com,.internal,10.0.0.0/8,.cluster.local,.cluster.onprem"
              DEST_PATH: /etc/environment
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: add-apt-proxy
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n\t\t\t\t\t\tAcquire::http::Proxy \"http://proxy-dmz.intel.com:912\";\n\t\t\t\t\t\tAcquire::https::Proxy
                \"http://proxy-dmz.intel.com:912\";"
              DEST_PATH: /etc/apt/apt.conf
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: write-hostname
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: |2-

                host-a5d75c46
              DEST_PATH: /etc/hostname
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: Write-Hosts-etc
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n127.0.0.1 host-a5d75c46\n            "
              DEST_PATH: /etc/hosts
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: add-dns-namespace
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: "\n\t\t\t\t\t\t[Resolve]\n\t\t\t\t\t\tDNS \"\""
              DEST_PATH: /etc/systemd/resolved.conf
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: write-netplan
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: |-
                network:
                                  version: 2
                                  renderer: networkd
                                  ethernets:
                                    id0:
                                      match:
                                        name: en*
                                      dhcp4: yes
              DEST_PATH: /etc/netplan/config.yaml
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0644"
              UID: "0"
          - name: update-netplan-to-make-ip-static
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 200
            environment:
              CONTENTS: |-
                #!/bin/bash
                while [ 1 ]
                do
                interface=$(ip route show default | awk '/default/ {print $5}')
                gateway=$(ip route show default | awk '/default/ {print $3}')
                sub_net=$(ip addr show | grep $interface | grep -E 'inet ./*' | awk '{print $2}' | awk -F'/' '{print $2}')
                if [ -z $interface ] || [ -z $gateway ] || [ -z $sub_net ]; then
                  sleep 2
                  continue
                else
                  break
                fi
                done
                # Define the network configuration in YAML format with variables
                config_yaml="
                network:
                  version: 2
                  renderer: networkd
                  ethernets:
                    id0:
                      match:
                        name: en*
                      dhcp4: no
                      addresses: [ 10.49.1.138/$sub_net ]
                      gateway4: $gateway
                      nameservers:
                        addresses: []
                "
                # Write the YAML configuration to the file
                echo "$config_yaml" | tee /etc/netplan/config.yaml
                ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
                touch .netplan_update_done
                netplan apply
              DEST_PATH: /home/postinstall/Setup/update_netplan_config.sh
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0755"
              UID: "0"
          - name: service-script-for-netplan-update
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 200
            environment:
              CONTENTS: |2-

                                                                [Unit]
                                                                Description=update the netplan with to make static ip
                                                                After=network.target
                                                                ConditionPathExists = !/home/postinstall/Setup/.netplan_update_done

                                                                [Service]
                                                                WorkingDirectory=/home/postinstall/Setup
                                                                ExecStart=/home/postinstall/Setup/update_netplan_config.sh

                                                                [Install]
                                                                WantedBy=multi-user.target
              DEST_PATH: /etc/systemd/system/update-netplan.service
              DIRMODE: "0755"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0644"
              UID: "0"
          - name: enable-update-netplan.service-script
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/cexec:1.2.2
            timeout: 200
            environment:
              CHROOT: "y"
              CMD_LINE: systemctl enable update-netplan.service
              DEFAULT_INTERPRETER: /bin/sh -c
              FS_TYPE: ext4
          - name: "add cloud-init config"
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              CONTENTS: |
                datasource:
                  Ec2:
                    metadata_urls: ["http://10.49.1.112:50061"]
                    strict_id: false
                manage_etc_hosts: localhost
                warnings:
                  dsid_missing_source: off
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              DIRMODE: "0700"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0600"
              UID: "0"
          - name: "add cloud-init ds-identity"
            image: 10.49.1.137:5000/one-intel-edge/edge-node/tinker-actions/writefile:1.2.2
            timeout: 90
            environment:
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: Ec2 
